# -*- coding: utf-8 -*-
"""Arithmetic_Expressions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAzCgRQcVDQ_t2qWAgyQM6J-e9O75uzr

Arithmetic Expressions Example 1
"""

sum = 2 + 2
difference = 9_123_421 - 1_305
product = 67 * 983
quotient = 189 / 9
remainder = 183 % 9
exponential = 2**2
floor_division = 9 // 2

print("Sum is:", sum)
print("Difference is:", difference)
print("Product is:", product)
print("Quotient is:", quotient)
print("Remainder is:", remainder)
print("Exponential is:", exponential)
print("Floor division is:", floor_division)

"""Example 2"""

num1 = 400
num2 = 20

sum_2 = num1 + num2
difference_2 = num1 - num2
product_2 = num1 * num2
quotient_2 = num1 / num2
remainder_2 = num1 % num2
exponential_2 = num1**num2
floor_division_2 = num1 // num2

print("Sum is:", sum_2)
print("Difference is:", difference_2)
print("Product is:", product_2)
print("Quotient is:", quotient_2)
print("Remainder is:", remainder_2)
print("Exponential is:", exponential_2)
print("Floor division is:", floor_division_2)

"""Order of Operations Examples"""

# easy example
example_1 = (14 - 7) / 7
print("Example 1 result is: " + str(example_1))

# challenging example
example_2 = ((((18 + 2) * 2) - 8) // 2) - 4 * 2

# Breakdown using order of operations to solve
# (18 + 2) = 20
# (20 * 2) = 40
# (40 - 8) = 32
# (32 // 2) = 16
# 4 * 2 = 8
# 16 - 8 = 8
print("Example 2 result is: " + str(example_2))

print(4 / 2)