# -*- coding: utf-8 -*-
"""C1M4L3Peer_Review_Quiz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W3NoVTioJhBkPw8ehJtZmuvkAWAMBXD3
"""

######################################################################################################################################
# For this quiz, write a short program that is able to compute the sum, difference, quotient, remainder, and product of two numbers. #
# Ask the user to input two numbers and have them select an operator to choose from (+,-,*,/,%). You will need to use conditional    #
# statements to match what arithmetic operator the user picked in order to perform the calculation. Once the user has input the two  #
# numeric values and an arithmetic operator, perform the calculation and display the output to the screen.                           #
######################################################################################################################################

# Welcome Message
print("Welcome to the basic calculator program!")
num1 = int(input("Enter a numeric value: "))
num2 = int(input("Enter another numeric value: "))
operator = input("Enter arithmetic operator to use (+,-,/,*,%): ")

# Initialize result
result = 0

def add(value1, value2):
  result = value1 + value2
  print("The sum is:", result)

def subtract(value1, value2):
  result = value1 - value2
  print("The difference is:", result)

def divide(value1, value2):
  result = value1 / value2
  print("The quotient is:", result)

def multiply(value1, value2):
  result = value1 * value2
  print("The product is:", result)

def remainder(value1, value2):
  result = value1 % value2
  print("The remainder is:", result)

if operator == "+":
  add(num1, num2)

elif operator == "-":
  subtract(num1, num2)

elif operator == "/":
  divide(num1, num2)

elif operator == "*":
  multiply(num1, num2)

elif operator == "%":
  remainder(num1, num2)

else:
  print("ERROR: Enter valid arithmetic operator...")