# -*- coding: utf-8 -*-
"""Conditional_Statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-WIFgV9pvHyxFnFMURicxJRjH-NaHRb_

Conditional Statements
"""

# Enter the If condition
if True:
  print("If condition is true!")
else:
  print("If condtion is false!")

# Enter the else condition
if False:
  print("If condition is true!")
else:
  print("If condtion is false!")

# Enter the elif condition
if False:
  print("If condition is true")
elif True:
  print("Elif condition is true")
else:
  print("If and Elif condition is false")

# Enter the else condition
if False:
  print("If condition is true")
elif False:
  print("Elif condition is true")
else:
  print("If and Elif condition is false")

"""Logical Operators in Coditional Statements"""

# Create a program that compares two integer values and prints out the max value
user_input_1 = int(input("Enter the first number: "))
user_input_2 = int(input("Enter the second number: "))

if (user_input_1 > user_input_2):
  print(user_input_1, "is greater than", user_input_2)
elif (user_input_2 > user_input_1):
  print(user_input_2, "is greater than", user_input_1)
elif (user_input_1 == user_input_2):
  print(user_input_2, "is equal to", user_input_1)
else:
  print(user_input_2, "is greater than", user_input_1)

"""Example 2"""

# Create a program that prints out what will happen if a student works hard and studys for long hours
work_hard = True
long_study_hours = False

if (work_hard and long_study_hours):
  print("You will do well in this course!")
elif (work_hard or long_study_hours):
  print("You will have to spend more study hours or work harder")
else:
  print("You will have to work harder and put in longer study hours")

"""Nested Conditional Statements"""

# Create a program that allows a user to open a lockbox if the passcode is correct and the door is not jammed
# Also take out the contents if there is anything in the box

lockbox_passcode = 123456
jammed_door = True
contents_inside = True

if ((lockbox_passcode == 12345) and not jammed_door):
  if contents_inside:
    print("Taking contents out of lockbox")
  else:
    print("No contents in lockbox")

elif ((lockbox_passcode == 12345) and jammed_door):
  print("Door is jammed. Can not open lockbox...")

elif ((lockbox_passcode != 12345) and not jammed_door):
  print("User must enter correct passcode...")

else:
  print("Please enter correct lockbox passcode and make sure the door is not jammed")