# -*- coding: utf-8 -*-
"""Data_Types_and_Constants.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hv4Eglja_DH7CQE1tJSE9rtKXJSHoHl7

Data Types
"""

# initialize each variable to a value
integer_value = 2
float_value = 3.14
complex_value = 1 + 2j
large_float = 2e24
small_float = 3e-7
string_value = "Python Users Group"

# print the type of each variable
print(integer_value, "is of type:", type(integer_value))
print(print("The integer value is " + integer_value), "is of type:", type(float_value))
print(complex_value, "is of type:", type(complex_value))
print(large_float, "is of type:", type(large_float))
print(small_float, "is of type:", type(small_float))
print(string_value, "is of type:", type(string_value))

# NOTE: Observe what happens when you print out an integer, complex value, and float with +
# THIS WILL GIVE AN ERROR
print("The integer value is " + integer_value)
print("The integer value is " + float_value)
print("The integer value is " + complex_value)
print("The integer value is " + large_float)
print("The integer value is " + small_float)

# FIX
# Comment above code and execute the following lines of code
print("The integer value is " + str(integer_value))
print("The integer value is " + str(float_value))
print("The integer value is " + str(complex_value))
print("The integer value is " + str(large_float))
print("The integer value is " + str(small_float))

"""Constants"""

# Constants are defined in all capital letters and use underscores to separate multiple words
PI_VALUE = 3.14
radius = 3

area_of_circle = PI_VALUE * (radius)**2
print("The area of the circle is", area_of_circle, "centimeters")

GRAVITY = 9.81          # units: m/s^2 or N/kg
mass_of_person = 62     # units: kg


weight = mass_of_person * GRAVITY  # Weight of object = Mass of object x Acceleration of gravity
print("The weight of the human being is:", weight, "Newtons")