# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZCeIrwSKpmuMJbzarPfCN01YuoEJK8m-

Functions - Example 1
"""

# Create a program that calculates total sales earned in a year for a pizza company
# Implement a function that takes in two inputs: Quantity Sold and Price per Unit
# Return the total sales for that year

total_sales = 0
quantity = 200_000 # measured in units
price = 12.50   # $12.50 per unit

def compute_annual_sales(quantity_sold, price_per_unit):
  total_sales = quantity_sold * price_per_unit
  return total_sales

print("Total sales this year are $" + str(compute_annual_sales(quantity, price)))

"""Functions - Example 2"""

# Create a function that determines the maximum number of two numbers given user input

user_input_1 = int(input("Enter first integer: "))
user_input_2 = int(input("Enter second integer: "))

def maximumNumber(num1, num2):
  if num1 > num2:
    return num1
  elif num2 > num1:
    return num2

print("The larger number is:", maximumNumber(user_input_1, user_input_2))

"""Functions - Example 3"""

# Create a function that takes a list of integers and multiples each item in the list by 2
# Return the updated list values and print it to the screen

list_of_integers_1 = [1,2,3,4,5]

def multiplyByTwo(numbers):
  for index in range(len(numbers)):
    numbers[index] = numbers[index] * 2
  return numbers

print(multiplyByTwo(list_of_integers_1))
print(list_of_integers_1) # NOTE: The previous list gets updated too because the original list and the modified list reference the original list

# NOTE: Using copy() solves above problem with the original list changing since your copy refers to a new list
list_of_integers_2 = [6,7,8,9,10]
updated_list = list_of_integers_2.copy()

print(multiplyByTwo(updated_list))
print(list_of_integers_2)