# -*- coding: utf-8 -*-
"""Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6r4vRLfopxGv5s7UnAIlYOkrEV8uRz0

While Loop - Example 1
"""

# Create a program that counts the number of iterations to 10
count = 0

while count < 10:
  print("Count is:", count)
  count = count + 1

"""While Loop - Example 2"""

# Create a program that counts the number of iterations to 10 while incrementing by 2
count_2 = 0

while count_2 < 10:
  print(count_2)
  count_2 += 2

"""Infinite Loop - Example"""

while True:
  print("Infinite Loop")

"""While Loop and Else - Example"""

# Create a program that simulates a washing machine lock
# If a break is inserted in the loop, the else statement will not execute since the condition was not completed naturally
# Else statement will only execute as long as the condition breask naturally (without a break statement)

machine_on = True
door_locked = True
time_limit_count = 1
rotation_per_minute = 0

time_limit = int(input("Enter a time limit (minutes) for load: "))
time_remaining = time_limit

while (door_locked and machine_on and time_remaining > 0):
  rotation_per_minute += 5
  time_remaining = time_remaining - time_limit_count
  print("Time remaining:", time_remaining, "minutes left")
  break
else:
  print("Machie powering down...")

print("Number of cycles executed:", rotation_per_minute)

"""For Loops"""

# Iterate over a range of numbers
n = 22
for index in range(0, n):
  print("Index:", index)

# Iterate from 5 to 12
for i in range(5, 13):
  print("Index:", i)

# Iterate throgh a list of fruits
fruits = ['apples', 'oranges', 'bananas', 'grapes']
for fruit in fruits:
  print("The fruit purchased are", fruit)

"""Nested Loops"""

# Iterate through a range of numbers 1 to 10 in an inner loop
# Iterate through a range of numbers 1 to 5 in an outter loop

for i in range(1, 6):
  print("Outter loop count is", i)
  for i in range(1, 11):
    print("Inner loop Count is", i)
  print("\n")