# -*- coding: utf-8 -*-
"""Math_Library_Examples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpwEhJM_QaRL8eYHysalQGOEUHmwMPco

Math Library Functions
"""

import math

# take the square root of 81
x = math.sqrt(81)
print("Square root of 81:", x)

# take the floor of 2.7
# floor will give you the least value
print("Floor of 2.7:", math.floor(2.7))

# take the ceiling of 2.2
# ceil will give you the highest value
print("Ceil of 2.2:", math.ceil(2.2))

# exponent example: 4**2 using math.pow
print("4 raised to the power of 2:", math.pow(4,2))

# print the value of pi
print("Pi Value:", math.pi)

# print the value of epsilon
print("Epislon Value:", math.e)

# import math using a shorter name (this is another option you can use)
import math as m

print(m.sqrt(25))
print(math.sqrt(36))

# now import a few functions from math using from
from math import sqrt, pow

x = sqrt(25)
y = pow(6, 2)

print(x)
print(y)

# find all the functions available in the math library
help('math')