# -*- coding: utf-8 -*-
"""Random_Library_Examples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17j6n5Jir9glB3n1k3qzCCEWLQkeKZ0LZ

Random Library Examples
"""

import random

# print a random value from a list of integers
my_list = [11, 24, 23, 30]
print(random.choice(my_list))

# print a random value from a tuple
my_tuple = (22.4, 19.4, 31.5, 33.2)
print(random.choice(my_tuple))

# print a random value from a string
my_string = 'Python'
print(random.choice(my_string))

# random numbers depend on a seeding value
# when the seed value is 5, the number generated will always be the same (not ideal for encryption)
random.seed(5)

print(random.random())
print(random.random())

# Generate a random integer using randint() which takes in a range of integers
print(random.randint(1,5))
print(random.randint(-7,-3))

# Generate a random float between 0.0 to 1 value using random()
print(random.random())

# Shuffle a list using the random library
fruits = ['apples', 'oranges', 'grapes', 'lemons']

print("List before shuffle:", fruits)
random.shuffle(fruits)
print("List after shuffle:", fruits)