# -*- coding: utf-8 -*-
"""Type_Conversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R9C0GhuTLCfY4QsjnGnXqbG0Cce1Btdk

Converting Integer to Float Example
"""

integer_value = 22
float_value = 3.14

updated_value = integer_value + float_value

print("data type of integer_value is:", type(integer_value))
print("data type of float_value is:", type(float_value), "\n")

print("Updated value:", updated_value)
print("data type of updated_value is:", type(updated_value))

"""Type Conversion Error Example"""

numeric_value = 246
string_value = "357"

print("Data type of numeric value:", type(numeric_value))
print("Data type of string value:", type(string_value))

print(numeric_value+string_value)

"""Explicit Type Conversion"""

numeric_value = 246
string_value = "357"

print("Data type of numeric value:", type(numeric_value))
print("Data type of string value:", type(string_value), "\n")

numeric_value_2 = int(string_value)

sum_value = numeric_value + numeric_value_2
print("Sum value is:", sum_value)
print("Data type of sum_value:", type(sum_value))