# -*- coding: utf-8 -*-
"""User_Input_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tcp_-3H18DD2lbTRkd21ACV6VUtTOCfC

Comments
"""

# Comments are denoted by the hashtag symbol
# Always comment your code
# Comments do not execute anything
# Comments are used by programmers to explain what a line of code or a code block does

######################################################################################
# Function Name:                                                                     #                                                           
#   Description of what the function does                                            #                               
######################################################################################

"""Print output to screen"""

# Use print() to display output to the screen
print("Hello World!")
print("Welcome to your first python program!\n")

user_name = "Tim"
print("Hello", user_name)

# Notice the differnce between these two statements
print("Is this your first program" + user_name + "?") 
print("Is this your first program " + user_name + "?")

"""Enter User Input"""

print("Welcome! My name is Beepy and I am your perosnal chatbot.")

# User input is passed in using input()
name_of_user = input("Enter your name here: ")
print("Nice to meet you " + name_of_user + "\n")

user_task = input("What can I do for you today? ")
print("I will " + user_task + " for you today.")

"""Another Input-Output Example"""

# variables defined to store student names as strings
first_student = "Amy"
second_student = "Bob"
third_student = "Tim"

print("Students in the class include", first_student, "and", second_student, "and", third_student) # print the students in the class

course_name = input("Enter the course the students should take: ") # request user to input a course
print("The students will take", course_name, "this semester.")