# -*- coding: utf-8 -*-
"""Widgets_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HywnRhd7Zo9pJkhZ0Ih1p2JgE1msyeQ
"""

#https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html
import ipywidgets as widgets

widgets.Password(
    value='password',
    placeholder='Enter password',
    description='Password:',
    disabled=False
)

button = widgets.Button(
    description='Click me',
    disabled=False,
    button_style='warning', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click me',
    icon='check' # (FontAwesome names without the `fa-` prefix)
)
button

widgets.ColorPicker(
    concise=False,
    description='Pick a color',
    value='blue',
    disabled=False
)

widgets.IntRangeSlider(
    value=[5, 7],
    min=0,
    max=10,
    step=1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
)