# -*- coding: utf-8 -*-
"""Dict_Init.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nV_R-wJ9DqbGe8NWOuhmMjufkFXUSehu
"""

dictionary1 = {} #Creates an empty dictionary
print(dictionary1)
print()

dictionary1 = {"firstName" : "Sam", "lastName" : "Simpson"}
print(dictionary1)
print()

accounts = [('Bob', 1922.32),
            ('Sam', 2310),
            ('Tina', 3294.34),
            ('Lisa', 542.32)]

dictionary2 = dict(accounts)
print(dictionary2)
print()

names = ["Bob", "Sam", "Tina", "Tammy"]
degrees = ["Computer Science", "Electrical", "BioMedical", "Mechanical"]
dictionary3 = {}
for i in range(len(names)):
  dictionary3[names[i]] = degrees[i]
print(dictionary3)

dictionary4 = dict(zip(names, degrees))
print(dictionary4)