# -*- coding: utf-8 -*-
"""Dict_Access.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HEgiU6HKwZcYIfQ4TSJFtNoFYXmOOHvC
"""

dictionary1 = {"firstName" : "Sam", "lastName" : "Simpson"}

print("First Name:", dictionary1["firstName"]) #Access key to print the data
print("Last Name:", dictionary1["lastName"]) #Access key to print the data
print()

dictionary1['Age'] = 23  #Add to the dictionary
print(dictionary1)
print()

dictionary1['Age'] = 19 #Updated age in dictionary
print(dictionary1)
print()

del dictionary1['Age'] #Removes Age
print(dictionary1)
print()

dictionary1.clear() #removes all elements 
print(dictionary1)
print()
del dictionary1 #removes dictionary1
print(dictionary1)
print()