# -*- coding: utf-8 -*-
"""Dictionary_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmuYxO4b9-KiWmEw_2tSdoFck5CBMypq
"""

#Exercise 1
#Write a program to check whether a given key exists
dictionary1 = {'1' : 'Bob', '2' : 'Tina', '3' : 'Sam', '4' : 'Jim' }

x = input("Enater value to check:")

if( x in dictionary1.keys()):
  print(True)
else:
  print(False)

#Exercise 2
#Write a program to iterate over the dictionary items using a for loop
dictionary1 = {'1' : 'Bob', '2' : 'Tina', '3' : 'Sam', '4' : 'Jim' }

for key, val in dictionary1.items():
  print(f"Value of key {key} is {val}")

#Exercise 3
#Write a program to map 2 lists into a dictionary
keys = ['Tim', 'Tina', 'Sam']
values = [2343, 4321, 3423]

dictionary2 = dict(zip(keys, values))

print(dictionary2)

#Exercise 4
#Write a program to concatinate two dictionaries in to a new dictionary
dictionary1 = {'1' : 'Bob', '2' : 'Tina', '3' : 'Sam', '4' : 'Jim' }
dictionary2 = {'Tim' : 2343, 'Tina' : 4321, 'Sam' : 3423}

dictionary1.update(dictionary2)

print(dictionary1)