# -*- coding: utf-8 -*-
"""TypesOfExceptions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WWfedqv_Yxb_6teafGulk_94hLhbw57f
"""

#Divide by zero
10*(1/0)

#Name error
4+spam*3

#Type Error
'2'+2