# -*- coding: utf-8 -*-
"""Lists_Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S16pEJ5WXj2QPYgCDJh2OeLE1zC76-UP
"""

list1 = [2, 32.3, 65, 2, 43] #Created a List

print() #Prints a blank line

x = list1.index(65) #x contains the location index of 65
print(x) #Prints the value of x
print() #Prints a blank line
x = list1.count(2) #x contains the number of instances of a certain value
print(x) #Prints the value of x
print() #Prints a blank line
list1.remove(2) #Removes the first instance of a value defined
print(list1) #Prints the value of the list1
print() #Prints a blank line
print(list1[1:3])