# -*- coding: utf-8 -*-
"""List_Sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu2BspF7oh1HBb-ieeAcOu-NlaLnwBNR
"""

list1 = [123.2, 'James', 'Tim'] #Created a List
list2 = [12, 32.3, 65, 2, 43] #Created a List
list3 = ['Mike', 'Tina', 'Sam']
print(list1)
print(list2)
print(list3)
print()
list1.reverse()
list2.sort()
list3.sort()
print(list1)
print(list2)
print(list3)
print()
#Careful --- Error
list1.sort()