# -*- coding: utf-8 -*-
"""Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NhWhz4PsmrzatijTy6WfyOLavjy_zMOC
"""

list1 = ['Mike', 123, 123.4, 'Sam', 34.1] #Created a List
list2 = [123.2, 'James', 'Tim'] #Created a List
list3 = [12, 32.3, 65, 2, 43] #Created a List

print (list1) #Display list1
print (list2) #Display list2
print (list3) #Display list3
print() #Prints a Blank Line
list4 = list1 + list2 #Uses '+' to Concatinate to Lists 
list1.append('a,b,c') #Appends 'a,b,c' to the list1 
list3.insert(2,12) #inserts 12 at index 2 in list3
list2.extend([7,6,5]) #extends the list by adding 7,6,5 to list2
print()#Prints a Blank Line
print (list1) #Display list1 
print (list2) #Display list2
print (list3) #Display list3
print (list4) #Display list4