# -*- coding: utf-8 -*-
"""Lists_Calls.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6Uj3ff69W407rYUco9VQLne2bpBDCFy
"""

list1 = ['Mike', 123, 123.4, 'Sam', 34.1] #Created a List
print (list1) #Display list1

x = list1[0]
y = list1[1:3]
z = list1[2:]
print()#Prints a Blank Line
print (x) #Display list1 
print (y) #Display list2
print (z) #Display list3