# -*- coding: utf-8 -*-
"""Matplot_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKMjwHYWUD-dcrLiXtzs2SyUyrbGa9tt
"""

import matplotlib.pyplot as plt
import numpy as np

xpoints = np.array([1, 2, 4, 6, 8])
ypoints = np.array([3, 8, 1, 10, 3])

plt.plot(xpoints, ypoints)
plt.show()

import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot([1, 2, 3, 4], [10, 20, 25, 30], color='blue', linewidth=3)
ax.scatter([0.3, 3.8, 1.2, 2.5], [11, 25, 9, 26], color='green', marker='^')
ax.set_xlim(0.5, 4.5)
plt.show()

import matplotlib.pyplot as plt
fig = plt.figure(figsize=(20,10))
ax1 = fig.add_subplot(121)
ax2 = fig.add_subplot(122)
ax1.bar([1,2,3],[3,4,5])
ax2.barh([0.5,1,2.5],[0,1,2])
plt.show()