# -*- coding: utf-8 -*-
"""Matplotlib_Intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ubg2HkEbHt-iEffENz5TEI1YFWvl3cNN
"""

import matplotlib.pyplot as plt

x = range(-75, 75, 10)
y = [x2**2 for x2 in x]
plt.plot(x, y, linestyle='--') #dashed line
y = [x2**2.2 for x2 in x]
plt.plot(x, y, linestyle=':') #dotted line
y = [x2**2.4 for x2 in x]
plt.plot(x, y, linestyle='-') #solid line
y = [x2**2.6 for x2 in x]
plt.plot(x, y, 'o--y', linewidth=2) #Plot points on a line also use marker='o'
y = [x2**1.6 for x2 in x]
plt.plot(x, y, '-.', linewidth=2, color='purple') #dash with dot
plt.xlabel("x Label")
plt.ylabel("y Label")
plt.ylim(-1000, 2000)
plt.axhline(0, label='y label')
plt.axvline(0,label='x label')
plt.savefig("quad.png")
plt.legend()
plt.show()