# -*- coding: utf-8 -*-
"""Matpotlib_Box.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mPka4IUYpfibwaxYJmgLUbJcRAVH1f1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/sample_data/box_plt_data.csv')
sns.boxplot(df['p1_satisfaction'])
plt.title('Insightful Boxplot Title', fontsize=14)
plt.xlabel('Satisfaction')
plt.xlim([1,6])
plt.xticks(np.arange(1,6,1))