# -*- coding: utf-8 -*-
"""Matplotlib_Histograms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d3A7trDyUHEoxf_cK8PegjQLm4A-Und4
"""

import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('/content/sample_data/data.csv')
ids = data['Responder_id']
ages = data['Age']

bins = [0, 10, 20, 30, 40, 50, 60, 70, 80]

plt.hist(ages, bins=bins, edgecolor='black', log=True)
plt.axvline(29, color = '#fc4f30', label='Age Median', linewidth=2)
plt.legend()

plt.title('Ages of Respondents')
plt.xlabel('Ages')
plt.ylabel('Total Respondents')
plt.show()