# -*- coding: utf-8 -*-
"""NumpyArrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QX-d1Xl0EWZ5ING5Fa4lCUDvf5BV1zcV
"""

import numpy as np

array1 = np.array([11,22,33]) #Single Array
print(array1)
print()
array2 = np.array([(11, 22, 33, 44), (55, 66, 77, 88)])
print(array2)
print()