# -*- coding: utf-8 -*-
"""Numpy_Operations3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CyTniSTJFsvoV3ZlVh5H77yePdAPMybE
"""

import numpy as np
import matplotlib.pyplot as pt

array1 = np.array([11, 22, 33, 44])
x = np.arange(0,4*np.pi, 0.2)
y = np.sin(x)
pt.plot(x, y)
pt.show()
print()
print("Exponential values: ", np.exp(array1))
print("Log values: ", np.log(array1))