# -*- coding: utf-8 -*-
"""Numpy_Operations2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VW758LhQOjl64NDva5jyrfqi7WL00Dsp
"""

import numpy as np

array1 = np.array([(99, 110, 120, 130), (140, 150, 160, 170)]) # Array
array2 = np.array([(11, 22, 33, 44), (55, 66, 77, 88)])
print("array1: ", array1)
print("array2: ", array2)
print()
print("Sum of an Axis: ", array2.sum(axis=0))
print("Square Root for each element: ", np.sqrt(array2))
print("Starndard Deviation", np.std(array2))
print("array1 - array2: ", array1-array2)
print()
print("array1 + array2: ", array1+array2)
print()
print("array1 * array2: ", array1*array2)
print()
print("array1 / array2: ", array1/array2)
print()
print("convert to a single columb: ", array1.ravel())

