# -*- coding: utf-8 -*-
"""Numpy_Operations1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHyKiWC_dwT6dRAWfwCoQA_NHZjSjkLB
"""

import numpy as np

array1 = np.array([11,22,33]) #Single Array
array2 = np.array([(11, 22, 33, 44), (55, 66, 77, 88)])
print("array1: ", array1)
print("array2: ", array2)
print()
print("Dimention is: ", array2.ndim) #Displays the dimention of the array
print("The byte siz is: ", array2.itemsize) #The bite size in memory
print("The data type is: ", array2.dtype) #Displays data type
print("The size is: ", array2.size) #Displays the size
print("The shape is: ", array2.shape) #Displays the shape
array3 = array2.reshape(4,2)  #Restructures the array
print("Array 3: ", array3) #Displays the new Array
print("Elements in index 2 from array2: ", array2[0:,2])  #Displays the elements of an array
print("Range of 5 values between 1 and 2", np.linspace(1,2, 5))  #Displays the rand of values divided equally
print("Min value: ", array1.min())  #Displays the min value in the array
print("Max value: ", array1.max()) #Displays the max value in the array
print("Sum value: ", array1.sum()) #Displays the sum  value of the array