# -*- coding: utf-8 -*-
"""Pandas_Headers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-W_cfyLNI3jK_hMfIlJDnQ9kiS2uGQzY
"""

import pandas as pd

conference1= pd.DataFrame({'Day':[1,2,3,4,5,6], 
             "Attendies":[1320, 921,967,1410,1405,1310], 
             "Overall Rating":[5,4.2, 4.1,3.8,4.6,4.4]
             }, index=[10, 20, 30, 40, 50, 60]) 
print(conference1)
print()

print(conference1.rename(columns={"Day": "Year"}))