# -*- coding: utf-8 -*-
"""Pandas_Slice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1laKZqPs07p28Li4oML9ul0fHzSE4Gds9
"""

import pandas as pd
 
conference= {'Day':[1,2,3,4,5,6], 
             "Attendies":[1320, 921,967,1410,1405,1310], 
             "Overall Rating":[5,4.2, 4.1,3.8,4.6,4.4]} 
df= pd.DataFrame(conference) 
print(df)
print()
print("Top 3 cells:")
print(df.head(3))
print()
print("Last 3 cells:")
print(df.tail(3))

