# -*- coding: utf-8 -*-
"""Read_Split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VsgI5b46TV_2EddFgCVHs_qGvAi5RpQH
"""

f = open("/content/sample_data/hello.txt", r)
text = f.read() #Reads in entire file as a String
print(text.split()) #Splits the string by spaces
print()
print(text.split(",")) #Specific charater
print()
print(text.split("ll")) #Specific charater