# -*- coding: utf-8 -*-
"""ReadException.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WWfedqv_Yxb_6teafGulk_94hLhbw57f
"""

while True:
  try:
    name = int(input("Please enter file name: "))
    f = open("/content/sample_data/"+name, "r")
    text = f.read() #Reads in entire file as a String
    print(text)
    break
  except IOError:
    print("Please re-enter the file name.")