# -*- coding: utf-8 -*-
"""ReadFile_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6JdFD5ZNz52xDzT2pMyz2Oj6lHTAx17
"""

#Read all the contents of a file and display.
f = open("/MobyDick.txt", 'r')
fileText = f.read()
print("Data from the File")
print(fileText)
f.close()

#Read all the data except line 2 from the file
f = open("/MobyDick.txt", 'r')
fileText = f.readlines()
for i in range(len(fileText)):
  if i == 1:
    pass
  else:
    print(fileText[i])

f.close()

#Ask user for a word and then display the number of times it occurs in the text

f = open("/MobyDick.txt", 'r')
fileText = f.read()
fileText = fileText.split()

count = 0

word = input("Please enter the word you would like to count: ")

for i in range(len(fileText)):
  if fileText[i] == word:
    count = count + 1
  else:
    pass

print("You have a total of ", count, " occurances.")