# -*- coding: utf-8 -*-
"""Set_Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Xb1sTNTpAH50ZEoE664NDvZqkvukq7E
"""

people = {'Britt', 'Sam', 'Tim', 'Jan'}

for x in people:
  print('Great Job ', x)