# -*- coding: utf-8 -*-
"""Set_Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aq-9MRY0oFdckvQwmF9MFDTn068k3kli
"""

set1 = {11, 22, 44, 55, 33} #Creates a Set
print(len(set1)) #Number of elements 
print()
print(max(set1)) #Returns the max value in the set
print()
print(min(set1)) #Returns the min value in the set
print()
print(sorted(set1)) #Sorts the set
print()
print(sum(set1)) #Adds the elements and returns the sum
print()