# -*- coding: utf-8 -*-
"""Set_Methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYBY25VoF6dH6-dNVrEImrcZCFNLBN1K
"""

set1 = {11, 22, 33, 44, 55} #Creates a Set
print(set1) 
print()
set1.add(66) #Adds 66 to the set
print(set1)
print()
set1.update([77,88,99]) #updates the set with list
print(set1)
print()
set1.remove(77) #removes 77 from the set
print(set1)
print()
set1.pop() #remoces the first element from the set
print(set1)
print()
set1.clear() #removes all the elements from the set
print(set1)
print()