# -*- coding: utf-8 -*-
"""Set_Types.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_wJUBI9MLJDttz8UYIWVrMbOsjChncz
"""

set1 = {11, 11, 22, 33, 44}
print(set1)
print()
set2 = set()
print(set2)
print()
set3 = set({1,2,3})
print(set3)
print()