# -*- coding: utf-8 -*-
"""Sets_init.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OiEL7SxtZQT-L7zXPoKCjq6rX1wEeaAm
"""

print(set())
print()
print(set(range(6)))
print()
print(set(range(2, 6)))
print()
print(set(range(1, 12, 2)))
print()
print(set(range(-1, -12, -2)))
print()