# -*- coding: utf-8 -*-
"""tuples_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kF0RNcR69o1GfKCQ4mtGak_9Q9xxmi9I
"""

#Reverse the tuple list
tuple1 = (10, 30, 50, 70, 90)

tuple1 = tuple1[: : -1]
print(tuple1)

#Print the value 50 from the tuple 
tuple1 = ([10, 20, 30, 40, 50], (60, 70, 80, 90), "Bob", "Tina", "Sam")

print(tuple1[0][4])

#Unpack the tuple into 5 different variables
tuple1 = (10, 30, 50, 70, 90)
value1 = tuple1[0]
value2 = tuple1[1]
value3 = tuple1[2]
value4 = tuple1[3]
value5 = tuple1[4]

print(value1)
print(value2)
print(value3)
print(value4)
print(value5)

#Sort the tuple by the 2nd element of the tuple
tuple1 = (('Bob', 27),('Tina', 17),('Sam', 34), ('Chris', 22))

temp = []

newTuple = ()

for n, t in tuple1:
  temp.append(t)

temp.sort()

for i in temp:
  for x,y in tuple1:
    if i == y:
      newTuple += (x,y)

print(newTuple)