# -*- coding: utf-8 -*-
"""tuple_types.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wgARvn0dk_pYQiKmi19LZDwL-92rSaj2
"""

tuple1 = {}
tuple2 = {12, 32.3, 65, 2, 43} #Created a tuple
print(tuple1)
print(tuple2)
print()

tuple3 = {'abc'}
print(tuple3, type(tuple3))
print()

tuple4 = ('abc', )
print(tuple4, type(tuple4))
print()

t5 = tuple('parrot')
print(t5)

print(t5[1:4])