# -*- coding: utf-8 -*-
"""Tuples_IterateList.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1la1xtFNiIGgJcI7E9rUnQ48LvwSBzr_q
"""

accounts = [('Bob', 1234, 1922.32),
            ('Sam', 2345, 2310),
            ('Tina', 3456, 3294.34),
            ('Lisa', 4567, 542.32)] #Created a List of Tuples: Name, Account Number, Balance


for x in accounts:  #for loop to iterate the tuple
  for y in x:
    print(y)
  print()


#Iterate using index with enumerate function
for index, tuple in enumerate(accounts):
  element_0 = tuple[0]
  element_1 = tuple[1]
  element_2 = tuple[2]
  print(element_0, element_1, element_2)