# -*- coding: utf-8 -*-
"""Tuples_ListConvert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yEjM6gAHdOBS5ryfYOV0GpKa-xKYCwTA
"""

list1 = [12, 32.3, 65, 2, 43] #Created a List
tuple1 = tuple(list1) #Convert list into a tuple built-in function
print(tuple1, type(tuple1)) #Print tuple
print()#Prints a blank line
tuple2 = tuple(i for i in list1) #Using a for loop to populate tuple
print(tuple2) #Print tuple
print()#Prints a blank line
tuple3 = (*list1, type(tuple1)) #Unpack list items to uild a tuple
print(tuple3)