# -*- coding: utf-8 -*-
"""Tuple_Slice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jbo06n2NiSuei4xNx5Cpcri6qZZ5dXcT
"""

tuple1 = (12, 32.3, 65, 2, 43, 86) #Created a tuple
print(tuple1)
print(tuple1[1:5]) #prints the 2nd element - 5th element
print(tuple1[:4]) #prints the 1st element - 4th element
print(tuple1[2:]) #prints the 3rd element - to the last element 
print(tuple1[:]) #prints all the elements
print(tuple1[: : 2]) #prints 1st element - last element with a step of 2