# -*- coding: utf-8 -*-
"""UsingExceptions_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/194q9eFhYOUwKDojppGfMrTPat3FSZnvS
"""

try:
    print(14/0)
except ZeroDivisionError:
    print("You can't divide by zero!")

try:
    # Open file in read-only mode
    with open("cantFindMyFile.txt", 'r') as f:
        f.write("Welcome to Python!")
except IOError as e:
    print("An error occurred:", e)

try:
    # Open file in write-mode
    f = open("CreateNewFile.txt", 'w')
    f.write("Welcome to Python!")
except IOError as e:
    print("An error occurred:", e)
finally:
    print("Closing the file now")
    f.close()

import sys

randomList = ['a', 0, 2]

for item in randomList:
    try:
        print("The entry is", item)
        r = 1/int(item)
        break
    except:
        print("Oops!", sys.exc_info()[0], "occurred.")
        print("Let's look at the next entry.")
        print()
print("The reciprocal of", item, "is", r)