# -*- coding: utf-8 -*-
"""Write_File.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sv9vr_pVu1hdX38ptr9asFYaBZGIScrC
"""

while True:
  try:
    fileOpen1 = open("Names.txt", "w") # Writes over the existing data
    fileOpen2 = open("Degress.txt", "a") # Appends to the file

    fileOpen1.write("Bob, Tim, Sam, Tina")
    fileOpen2.write("CSE, CS, MAT, ENG")

    fileOpen1.close()
    fileOpen2.close()
    break
  except IOError:
    print("Please re-enter the file name.")