# -*- coding: utf-8 -*-
"""WritingFile_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vR1CXGNbctH66h4OUvu1qDnvlso4xLMM
"""

#Write the contents of a file to a new file.
#r - Read, a - Append, w - Write, x - Create, t - text, b - binary

f = open("/content/MobyDick.txt", 'r')
fileText = f.read()
print("Moby Dick Chapter 1")
print(fileText)

f = open("Updated.txt", 'w')
f.write(fileText)

f = open("Updated.txt", 'r')
fileText = f.read()
print("Data from the new file")
print(fileText)
f.close()

#Write a program that will rename a file
import os

f = open("/content/MobyDick.txt", 'r')
fileText = f.read()
f.close()

f= open("NewFile.txt", 'w')
f.write(fileText)
f.close()

os.remove("/content/MobyDick.txt")
os.rename("NewFile.txt", "MobyDick1.txt")

